Numpy:Package for multidimensional array


In [1]:
import numpy as np

In [2]:
sample_list=[6,7,9]
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.array(sample_list)

array([6, 7, 9])

In [4]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [5]:
lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1,30,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [10]:
np.arange(0,51)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [11]:
np.arange(5,26,5)

array([ 5, 10, 15, 20, 25])

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.zeros(100,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [17]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.ones((2,5),int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [20]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
np.linspace(0,4,4)

array([0.        , 1.33333333, 2.66666667, 4.        ])

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [29]:
np.random.rand(2,4)

array([[0.67293205, 0.22233368, 0.64875818, 0.25310805],
       [0.78560854, 0.58566864, 0.39765363, 0.11883265]])

In [32]:
np.random.randn(2,4)

array([[ 0.74699329,  0.33155252,  0.34914946, -2.03437413],
       [ 0.46260176, -0.02745873, -1.3588428 , -0.36673828]])

In [33]:
np.random.randint(2,100)

36

In [34]:
np.random.randint(20,56,100)

array([47, 44, 51, 30, 26, 48, 54, 38, 35, 20, 30, 25, 37, 20, 41, 36, 37,
       44, 40, 34, 38, 21, 40, 36, 24, 39, 28, 28, 41, 37, 39, 40, 44, 23,
       45, 26, 50, 27, 45, 35, 50, 40, 40, 23, 21, 25, 40, 52, 26, 20, 31,
       52, 51, 45, 26, 26, 42, 41, 55, 38, 26, 35, 42, 36, 52, 41, 45, 26,
       40, 48, 25, 20, 36, 55, 50, 49, 30, 51, 52, 34, 22, 26, 26, 21, 23,
       30, 38, 28, 42, 33, 27, 26, 27, 45, 25, 41, 30, 39, 44, 54])

In [36]:
np.random.randint(0,100,10)

array([15, 96, 62, 94, 25, 25,  5,  9, 99, 82])

In [37]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [38]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [39]:
sample_array.min()

0

In [40]:
sample_array.argmin()

0

In [41]:
sample_array.max()

29

argmax() gives index of max value


In [42]:
sample_array.argmax()

29

In [43]:
sample_array[8]

8

In [44]:
sample_array[2:5]

array([2, 3, 4])

In [45]:
sample_array[1:4]=100

In [46]:
sample_array

array([  0, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [47]:
sample_array[0:7]

array([  0, 100, 100, 100,   4,   5,   6])

In [48]:
sub_sample=sample_array[0:7]
sub_sample

array([  0, 100, 100, 100,   4,   5,   6])

In [49]:
sub_sample[:]=1001
sub_sample

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

2D array


In [51]:
sample_matrix=np.array(([1,2,3],[4,5,6],[7,8,9]))
sample_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
sample_matrix[0][2]

3

In [53]:
sample_matrix[2]

array([7, 8, 9])

In [54]:
sample_matrix[0,2]

3

In [55]:
sample_matrix[2,:]

array([7, 8, 9])

In [58]:
sample_matrix[:2,2]

array([3, 6])